# Generated by Django 3.0.7 on 2022-05-04 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contactme',
            new_name='Contactus',
        ),
    ]
